### ISSUE TITLE
Modules deprecation

### ISSUE THREAD

**Issue by ghost** [splunk/addonfactory-ta-library-python#38]
`splunktalib` and `solnlib` (https://github.com/splunk/addonfactory-solutions-library-python) have same modules / classes / functions. This issue tracks deprecation of the duplicate functionality in `splunktalib`.

Deprecate following modules (sorted alphabetically):

- [x] common.consts (#42)
- [x] common.log (#42)
- [x] common.pattern (#42)
- [x] common.util.datetime_to_seconds (#42)
- [x] common.util.handle_tear_down_signals (#42)
- [x] common.util. remove_http_proxy_env_vars (#51) 
- [x] common.util.is_false (#42)
- [x] common.util.is_true (#42)
- [x] credentials (#42)
- [x] event_writer (#42)
- [x] file_monitor (#39)
- [x] kv_client (#42)
- [x] orphan_process_monitor (#37)
- [x] splunk_platform.get_splunk_bin (#42)
- [x] splunk_platform.make_splunkhome_path (#42)
- [x] timer (#42)
- [x] timer_queue (#42)
- [x] splunk_cluster (#37)

Migration to `solnlib` (sorted alphabetically):

- `splunktalib.common.log` -> `solnlib.log`
- `splunktalib.credentials` -> `solnlib.credentials`
- `splunktalib.event_writer` -> `solnlib.modular_input.event_writer`
- `splunktalib.timer_queue` -> `solnlib.timer_queue`
- `splunktalib.timer` -> `solnlib.timer_queue`

You should not use it directly:

- `splunktalib.common.consts`

Just rename the import:

- `splunktalib.common.util.datetime_to_seconds` -> `solnlib.utils.datetime_to_seconds`
- `splunktalib.common.util.handle_tear_down_signals` -> `solnlib.utils.handle_teardown_signals`
- `splunktalib.common.util.is_false` -> `solnlib.utils.is_false`
- `splunktalib.common.util.is_true` -> `solnlib.utils.is_true`
- `splunktalib.common.util.remove_http_proxy_env_vars` -> `solnlib.utils.remove_http_proxy_env_vars`
- `splunktalib.pattern` -> `solnlib.pattern`
- `splunktalib.orphan_process_monitor` -> `solnlib.orphan_process_monitor`
- `splunktalib.splunk_platform.get_splunk_bin` -> `solnlib.splunkenv.get_splunk_bin`
- `splunktalib.splunk_platform.make_splunkhome_path` -> `solnlib.splunkenv.make_splunkhome_path`

Code change required:

- `splunktalib.file_monitor.FileMonitor` -> `solnlib.file_monitor.FileChangesChecker`

    Migration example:

    Before:
    ```python
    from splunktalib import file_monitor

    class ConfMonitor(file_monitor.FileMonitor):
        def __init__(self, callback):
            super(ConfMonitor, self).__init__(callback)

        def files(self):
            return <files to monitor>

    conf_monitor = ConfMonitor(callback)
    ```

    After:
    ```python
    from solnlib import file_monitor

    conf_monitor = file_monitor.FileChangesChecker(
        callback, <files to monitor>
    )
    ```

- `splunktalib.splunk_cluster` -> `solnlib.server_info`

    Migration example:

    Before:
    ```python
    from splunktalib import splunk_cluster

    sc = splunk_cluster.ServerInfo(<splunkd_uri>, <session_key>)
    print(sc.is_search_head())
    # Or any other method from splunk_cluster.ServerInfo
    ```

    After:
    ```python
    from solnlib import server_info

    sc = server_info.ServerInfo.from_server_uri(<splunkd_uri>, <session_key>)
    print(sc.is_search_head())
    ```

- `splunktalib.state_store` -> `solnlib.modular_input.checkpointer`

    Only KV Store-based checkpointer is a preffered way to handle checkpoints.

    `splunktalib.state_store.CachedFileStateStore` and `splunktalib.state_store.FileStateStore` should not be used and should be migrated to KV Store-based checkpointer.

    Migration example:

    Before:
    ```python
    from splunktalib import state_store

    checkpoint = state_store.StateStore(
        {
            "server_uri": <server_uri>,
            "session_key": <session_key>,
        },
        APP_NAME,
        collection_name=<collection_name>
    )
    checkpoint.update_state(
        <key>,
        <states>
    )
    print(checkpoint.get_state(<key>))
    checkpoint.delete_state(<key>)
    ```

    After:
    ```python
    from solnlib.modular_input import checkpointer

    checkpoint = checkpointer.KVStoreCheckpointer(
        <collection_name>,
        <session_key>,
        APP_NAME,
        # optional scheme, host, port params
    )
    checkpoint.update(<key>, <states>)
    print(checkpoint.get(<key>))
    checkpoint.delete(<key>)
    ```

**Comment by arys-splunk** [comment]
#37 introduces depreciation of those classes.
